config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  get '/welcome', to: 'welcome#index'
  root 'welcome#index'

  resources :users do 
    resources :trips
  end

  resources :trips do
    resources :attendees
  end

  resources :trips, shallow: true do
    resources :expenses
  end

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :trip
  has_many :expenses, dependent: :destroy
  validates :name, presence: true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :attendee
  has_one :trip, through: :attendee
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :attendees, dependent: :destroy
  has_many :expenses, through: :attendees, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
	  user_trips_path(current_user)
	end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController



	def create
		@trip = Trip.find(params[:trip_id])
		@attendee = @trip.attendees.create(attendee_params)
		@attendee.save
		redirect_to trip_path(@trip)

		# if @attendee.save 
		# redirect_to new_trip_path(@trip)
		# else
		# render 'new'
		# end
	end 

	def destroy
		@trip = Trip.find(params[:trip_id])
		@attendee = @trip.attendees.find(params[:id])

		#@attendee = Attendee.find(params[:id])
		@attendee.destroy
		#redirect_to root_path
		redirect_to trip_path(@trip)
	end 

	def attendee_params
		params.require(:attendee).permit(:name, :trip_id)
	end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	def index
		@trip = Trip.find(params[:trip_id])
		@expenses = @trip.expenses.order(:date) 


	end

	def new
		@trip = Trip.find(params[:trip_id])
		@expense = Expense.new
	end


	# def create
	# 	@trip = Trip.find(params[:trip_id])
	# 	@expense = @trip.expenses.create(expense_params)
	# 	redirect_to trip_expense_path(@trip,@expense)

	# end

	def create
		
		#@trip = Trip.find(params[:trip_id])
		@expense = Expense.new(expense_params)
		#@expense = @trip.expenses.create(expense_params)

		if @expense.save 
			redirect_to trip_expenses_path(@expense.trip)
		else
			render 'new'
		end
	end 

	def show
		# @trip = Trip.find(params[:trip_id])

		# @expense = Expense.find(params[:id])

		@expense = Expense.find(params[:id])

	end 


	# def edit
 #  		@expense = Expense.find(params[:id])

	# end

	# def update
	# 	@expense = Trip.find(params[:id])
		
	# 	if @trip.update(trip_params)
	# 	redirect_to @trip
	# 	else
	# 	render 'edit'
	# 	end 
	# end 

	def destroy
		expense = Expense.find(params[:id])

		trip = expense.trip

		expense.destroy

		redirect_to trip_path(trip)

		# Expense.delete(params[:id])
		# @trip = Trip.find(params[:trip_id])
		# @expense = @trip.expenses.find(params[:id])

		# #@expense = expense.find(params[:id])
		# @expense.destroy
		# #redirect_to root_path
		# redirect_to trip_path(@trip)

	end 

	def expense_params
		params.require(:expense).permit(:date, :payer, :description, :amount, :attendee_id)
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	def index
		@user = current_user
		@trips = @user.trips.order(:name) 
	end 

	def new
		@user = current_user
		@trip = @user.trips.build
	end

	def create
		
		@user = current_user
		@trip = @user.trips.create(trip_params)

		if @trip.save 
		redirect_to @trip
		else
		render 'new'
		end
	end 

	def show
		@trip = Trip.find(params[:id])
		@attendee = Attendee.new
		@expenses = @trip.expenses

	end 

	def edit
  		@trip = Trip.find(params[:id])
	end

	def update
		@trip = Trip.find(params[:id])
		
		if @trip.update(trip_params)
		redirect_to @trip
		else
		render 'edit'
		end 
	end 

	def destroy
		@trip = Trip.find(params[:id])
		@trip.destroy
		redirect_to trips_path
	end 

	private

    def trip_params
		params.require(:trip).permit(:name, :number, :user_id)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = current_user
  	@trips = Trip.all.order(:name)
  	# if user_signed_in?
  	# 	redirect_to user_trips_path(current_user)
  	# end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendees/_attendee.html.erb
	<%# @trip.attendees.each do |a| %>
 		<%#= a.name %>
 		<%# end %>
 		<%#= link_to "remove attendee", [attendee.trip, attendee], 
 			method: :delete, 
 			data: {confirm:  "Are you sure?"} %>


 <p>	
 			
 		<strong><%= attendee.name %></strong>
 		<%= link_to "remove attendee", trip_attendee_path(@trip, attendee), 
 			method: :delete, 
 			#data: {confirm:  "Are you sure?"},
 			:class => 'btn btn-danger btn-xs' %>

 </p>

app/views/attendees/_form.html.erb
<p>Add new attendee:</p>
<%=simple_form_for [@trip, @attendee] do |f|%>
	<%= f.input :name, label: false, placeholder: 'Name', autofocus:true %>
	</br>
	<%= f.submit %> 
<% end %>

app/views/expenses/_form.html.erb
<div class = "form-inputs">
	<%=simple_form_for [@trip, @expense] do |f|%>
		<%= f.input :date, label: 'Date:'%>
		</br>
		<label>Payer:</label><%= f.collection_select :attendee_id, @trip.attendees.order(:name),:id,:name, include_blank: false %>
		</br>
		</br>
		<label>Expense detail:</label><%= f.input :description, label: false %>
		</br>
		<%= f.input :amount, label: 'Amount paid:'%>
		<%= f.submit %>
		</br></br></br></br>
	<% end %>
</div>

app/views/expenses/_list.html.erb
<div class = "table-and-summary">
  <div class = "col-sm-9">
  <body>
  <h1>Expenses</h1>
  <table id="expenses" class="display" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Date</th>
        <th>Payer</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%= expense.date %></td>
          <td><%= expense.attendee.name if expense.attendee %></td>
          <td><%= expense.description %></td>
          <td>$<%= expense.amount %></td>
          <td><%= link_to "remove expense", expense, 
                  method: :delete, 
                  data: {confirm:  "Are you sure?"},
                  :class => 'btn btn-danger btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add new expense', new_trip_expense_path(@trip), :class => 'btn btn-primary' %>
  </div>

  <div class = "col-sm-3">
    <div class = "summary">
    <h1>Summary</h1>
    
    <ul>
      <% @trip.attendees.each do |attendee| %>
              <li>
              <%if attendee.expenses.sum(:amount) - (@trip.expenses.sum(:amount)/@trip.number) < 0  %>
              
              <p><%= attendee.name %> should pay: -<%= number_to_currency((@trip.expenses.sum(:amount)/@trip.number - attendee.expenses.sum(:amount))) %></p>
              <%else%>
               <p><%= attendee.name %> should receive: <%= number_to_currency(attendee.expenses.sum(:amount) - (@trip.expenses.sum(:amount)/@trip.number)) %></p>  
               <%end%> 
               </li>   
      <%end%>

    </ul>
    </br></br>
      <div class = "total">
        <h5>Total expenses: <%= number_to_currency(@trip.expenses.sum(:amount)) %></h5>
        <h5>Total expenses each: <%= number_to_currency(@trip.expenses.sum(:amount)/@trip.number) %></h5>
      </div>
    </div>
  </div>
  </body>
</div>



  

app/views/expenses/edit.html.erb
<%= render 'form' %>

app/views/expenses/index.html.erb
<style>
.back{
	margin-left: 70%
}
body{
	background: -webkit-linear-gradient(#d0eaee, #FFF); /* For Safari 5.1 to 6.0 */
	 background: -o-linear-gradient(#d0eaee, #FFF); /* For Opera 11.1 to 12.0 */
	 background: -moz-linear-gradient(#d0eaee, #FFF); /* For Firefox 3.6 to 15 */
	 background: linear-gradient(#d0eaee, #FFF); /* Standard syntax */
	 background-repeat: no-repeat;
}	
</style>
</style>

<div class = expense-index>
<%= render 'list' %>
</br>

	<div class = "col-sm-12">
		<div class = "back">
			</br>
			</br>
			</br>
			</br>
			<%= link_to 'Back', user_trip_path(current_user,@trip), :class => 'btn btn-info' %>
			</br>
			</br>
			</br>
			</br>
		</div>	
	</div>

</div>

app/views/expenses/new.html.erb
<style>
body{
	background: -webkit-linear-gradient(#d0eaee, #FFF); /* For Safari 5.1 to 6.0 */
	 background: -o-linear-gradient(#d0eaee, #FFF); /* For Opera 11.1 to 12.0 */
	 background: -moz-linear-gradient(#d0eaee, #FFF); /* For Firefox 3.6 to 15 */
	 background: linear-gradient(#d0eaee, #FFF); /* Standard syntax */
	 background-repeat: no-repeat;
}	
</style>


<body>
<%= render 'form' %>
</body>

app/views/expenses/show.html.erb
<h1>Expenses</h1>
<table id="expense_lists" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Date</th>
      <th>Payer</th>
      <th>Description</th>
       <th>Amount</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @expense.date %></td>
        <td><%= @expense.payer %></td>
        <td><%= @expense.description %></td>
        <td><%= @expense.amount %></td>
      </tr>
  </tbody>
</table>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Home', root_path, :class => "navbar-brand topnav" %>
                <% if user_signed_in? %>
                <%= link_to 'My Trips', user_trips_path(current_user), :class => "navbar-brand topnav" %>
                <% end %>
                <%#= link_to 'What is Treasure?', root_path, :class => "navbar-brand topnav" %>
                <%#= link_to 'About Us?', root_path, :class => "navbar-brand topnav" %>
                <%#= link_to 'Contact Us?', root_path, :class => "navbar-brand topnav" %>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to 'What is Treasure?', welcome_path(:anchor => "about") %>
                          <!-- used to be #about -->
                    </li>
                    <li>
                        <a href="/#services">About Us</a>
                        <!-- used to be #services" -->
                    </li>
                    <li>
                        <a href="/#contact">Contact Us</a>
                        <!-- used to be #contact -->
                    </li>
                    <% if user_signed_in? %>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                        </ul>
                      </li>
                    <% else %>
                      <%#= link_to 'What is Treasure?', root_path, :class => "navbar-brand topnav" %>
                      <%#= link_to 'About Us?', root_path, :class => "navbar-brand topnav" %>
                      <%#= link_to 'Contact Us?', root_path, :class => "navbar-brand topnav" %>
                      <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                      <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treasure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<% if notice %>
  <p class="alert alert-success an-zindex"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger an-zindex"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/trips/_form.html.erb
<div class = "trip-form">
	<%=simple_form_for @trip do |f|%>
		<h3>Where are you guys going?</h3>
			<%= f.input :name, label: false, placeholder: 'Ex: California', autofocus: true %>
		<h3>How many people?</h3>
			<%= f.input :number, label: false, placeholder: 'Ex: 4'%>
			<br>
			<br>
			<%= f.submit %>
	<% end %>
</div>

	

app/views/trips/edit.html.erb
<h1>Edit Trip</h1>
<%= render 'form' %>

app/views/trips/index.html.erb
<style>
	body{
		background: url(/assets/welcome.JPG);
		background-size: cover;
		text-align: center;
	}
	
	.new{
		margin: 6% 20% auto 15%;
	}
</style>

<div class = "container navpad">
	<div class = "row">
		<div class = "col-lg-12">
			<div class = "container navpad">
				<body>
					<div class = "new">
						<div class = trip-index>
						<h1>Welcome!</h1>
						<h3><%= link_to "Add New Trip", new_user_trip_path(@user), :class => 'btn btn-success btn-lg'%></h3>

						<h4>Here are your recent trips:</h4>
							<%@trips.each do |trip|%>
							<p><%= link_to trip.name, trip_path(trip) %></p> 
						<%end%>

						</div>
					</div>
				</body>
			</div>
		</div>
	</div>
</div>

app/views/trips/new.html.erb
<style>
	body{
		background: linear-gradient(0deg, #d0eaee, #ffffff);
		
	}
	.back{
		margin: auto 51% auto 49%;
		padding-top: 10%;
	}
</style>

<!-- <h1>Add New Trip</h1> -->
<div class = "container navpad">
	<div class = "row">
		<div class = "col-lg-12">
			<div class = "container navpad">
				<body>
				<%= render 'form' %>
				</body>
			</div>
		</div>
	</div>
</div>

<div class = "back">
<%= link_to 'Back', root_path, :class => 'btn btn-primary' %>
</div>

app/views/trips/show.html.erb
<style type="text/css">
	.trip-form {
		text-align: center;
	}
	.trip-index {
		text-align: center;	
	}
	.trip-show {
		margin: 3% 3% 3% 3%;
		text-align: center;
		padding: 2%;
		min-height: 100%;
 	}
 	body {
 		background: -webkit-linear-gradient(#d0eaee, #FFF); /* For Safari 5.1 to 6.0 */
 		 background: -o-linear-gradient(#d0eaee, #FFF); /* For Opera 11.1 to 12.0 */
 		 background: -moz-linear-gradient(#d0eaee, #FFF); /* For Firefox 3.6 to 15 */
 		 background: linear-gradient(#d0eaee, #FFF); /* Standard syntax */
 		 background-repeat: no-repeat;
 	}
	.buttons{
		margin-left: 70% ;
	}
</style>
<div class="trip-show">
	<h1><strong><%= @trip.name %></strong></h1>
	  
	<p> Number of Attendees: <%= @trip.number %></p>

	<strong><p> Who's coming: </p></strong>
	<%= render @trip.attendees %>
	 	
	<%if @trip.attendees.size < @trip.number %> 

	<p><%= render 'attendees/form' %></p>
	<%end%>


	<h1>__________________________________________________________________</h1>

	<%= render 'expenses/list' %>
	<%#= link_to 'Add new expense', new_trip_expense_path(@trip), :class => 'btn btn-primary' %>
 
	<div class = 'buttons'>

		<div class = "col-lg-12">
		</br>
		</br>
		</br>
		</br>
			<%= link_to 'Edit', edit_trip_path(@trip), :class => 'btn btn-primary'%>
			<%= link_to 'All trips', trips_path, :class => 'btn btn-info' %>
			<%= link_to 'Delete this trip', trip_path(@trip),
			              method: :delete,
			              data: { confirm: "Are you sure?" },
			              :class => 'btn btn-danger' %>
		</br>
		</br>
		</br>
		</br>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
    <!-- Header -->

    <style>

    .img-center {
      margin: 0 auto;
      display: inherit;
      padding: 0 0 20px 0;
    }

    .questions {
      font-size: 50px;

    }

    .free {
      font-size: 20px;
    }

/*    body {
        background: #FFF;
    }*/

    </style>
   
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>welcome to treasure</h1>
                        <h3>Treasure these moments</h3>
                        <h3>Account the journey</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <!-- <li>
                                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li> -->
                            <!-- <li>
                                <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Start</span></a>
                            </li> -->
                            <li>
                               <!--  <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"></i> <span class="network-name">Start Yours Now</span></a> -->
                                <%= link_to 'Start Yours Now', new_user_registration_path, :class => "btn btn-default btn-lg network-name" %>
                            </li>
                            <!-- <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->
    <a  name="about"></a>
    <div class="content-section-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Treasure is made to keep things simple.</h2>
                    <p class="lead">Treasure helps you to divide mutual spending between you and your friends so that the focus of your trip is on the people around you and not the money spent.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                 <img class="img-responsive" src="../img/phones.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row row-centered">
                <div class="col-lg-6 col-centered">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Sihan Ding</h2>
                    <!--enter picture -->
                    <div class = "han-img">
                     <img  height="325" width ="300" class ="img-circle img-center" class="img-responsive" src="../img/ipad.png" alt="">
                     </div>
                    <p class="lead">Sihan will be a rising third year at the University of Virginia, McIntire School of Commerce majoring in Finance. His inspiration for this app stems from his experiences with planning for large groups of people and created a solution for more organized group travel. In his spare time, Han likes to take stunning pictures and improve his talents in photography.</p>
                </div>
                 <div class="col-lg-6 col-centered">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Gloryah Allen</h2>
                    <!--enter picture -->
                    <div class = "glo-img">
                     <img class ="img-circle img-responsive img-center" src="../img/dog.png" height ="300" width ="300" alt="">
                     </div>
                    <p class="lead">Gloryah will also be a rising third year at the University of Virginia double majoring in Economics + Studio Arts. Her goal for this app was to create a sleek and easy to use UX design for any group organizer, for any type of trip. In her spare time, Gloryah plays percussion music and drives buses.</p>
                </div>
                <!-- <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="img/ipad.png" alt="">
                </div> -->
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-12 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading" >
                    <div class="questions">Have any questions?</div>
                    <p class="lead"><div class ="free">Please feel free to connect with us on LinkedIn</a>.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
              <!-- need to fix responsiveness when page is small -->
                <div class="col-lg-3 col-sm-1">
                    <!-- <h2>Connect to Treasure:</h2> -->
                   <ul class="list-inline banner-social-buttons">
                        <li>
                             <a href="https://www.linkedin.com/in/designding" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Sihan's Linkedin</span></a>
                        </li>
                      </ul>
                </div>
                
                <div class="col-lg-9 col-sm-1">
                    <ul class="list-inline banner-social-buttons">
                      <li>
                            <a href="https://www.linkedin.com/in/gloryahallen" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Gloryah's Linkedin</span></a>
                        </li>
                       <!--  <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li> -->
                        <!-- <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li> -->
                      
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">What is Treasure</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">About Us</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact Us</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Treasure 2015. All Rights to Happiness Reserved</p>
                </div>
            </div>
        </div>
    </footer>

</body>